sudo: false
language: python
python:
  - "3.7"

before_install:
  - pip install pipenv
  - pipenv install codecov

install:
  - pipenv install --dev

script:
  - cd test_project
  - coverage run --source ../versionfield manage.py test versionfield 

after_success:
  - codecov
