sudo: false
language: python
python:
  - "2.7"

before_install:
  - pip install codecov
  - python setup.py -q install

script:
  - cd test_project
  - coverage run --source ../versionfield manage.py test versionfield 

after_success:
  - codecov
